version: '3.8'

services:
  bot:
    build: ..
    image: discord_bot:latest
    container_name: my_discord_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /app/data
    
