FROM python:3.11 AS base_builder
WORKDIR /app/

COPY base-requirements.txt .
RUN python -m pip install --no-cache-dir -r base-requirements.txt && rm base-requirements.txt

FROM gcr.io/distroless/python3-debian12:debug-nonroot AS base_runner
ENV PYTHONPATH="/python-base-packages:/python-extra-packages"
COPY --chown=nonroot:nonroot --from=base_builder /usr/local/lib/python3.11/site-packages/ /python-base-packages/

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#                              slow stuff goes above this line for docker cache
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

FROM base_builder AS repo_builder
ARG CACHE_BUST=${CACHE_BUST}
ADD https://github.com/LeightonSmallshire/iter8-bot.git /app/
RUN python -m pip install --no-cache-dir -r requirements.txt


FROM base_runner AS final_runner
COPY --chown=nonroot:nonroot --from=repo_builder /app/ /app/
COPY --chown=nonroot:nonroot --from=repo_builder /usr/local/lib/python3.11/site-packages/ /python-extra-packages/

WORKDIR /app
ENTRYPOINT ["python3"]
CMD ["main.py"]
