#FROM python:3.11 AS base_builder
#
#COPY base-requirements.txt /
#RUN python -m pip install --no-cache-dir -r /base-requirements.txt
#
##ARG CACHE_BUST=${CACHE_BUST}
#ADD https://github.com/LeightonSmallshire/iter8-bot.git /app/
#RUN python -m pip install --no-cache-dir -r /app/requirements.txt
#ENV PYTHONPATH="/usr/local/lib/python3.11/site-packages/"
#
#WORKDIR /app
#ENTRYPOINT ["python3"]
#CMD ["main.py"]
